#!/bin/bash

make distclean > /dev/null 2>&1

rm -rf ./INSTALL
rm -rf ./Makefile 
rm -rf ./Makefile.in
rm -rf ./aclocal.m4
rm -rf ./autom4te.cache
rm -rf ./config.guess
rm -rf ./config.h
rm -rf ./config.h.in*
rm -rf ./config.log
rm -rf ./config.status
rm -rf ./config.sub
rm -rf ./configure
rm -rf ./depcomp
rm -rf ./install-sh
rm -rf ./minimal.list
rm -rf ./libtool
rm -rf ./ltmain.sh
rm -rf ./missing
rm -rf ./yapp-*.tar.gz
rm -rf ./src/yapp/Makefile
rm -rf ./src/yapp/Makefile.in
rm -rf ./src/yapp/admin/Makefile
rm -rf ./src/yapp/admin/Makefile.in
rm -rf ./src/yapp/base/Makefile
rm -rf ./src/yapp/base/Makefile.in
rm -rf ./src/yapp/client/Makefile
rm -rf ./src/yapp/client/Makefile.in
rm -rf ./src/yapp/domain/Makefile
rm -rf ./src/yapp/domain/Makefile.in
rm -rf ./src/yapp/master/Makefile
rm -rf ./src/yapp/master/Makefile.in
rm -rf ./src/yapp/util/Makefile
rm -rf ./src/yapp/util/Makefile.in
rm -rf ./src/yapp/worker/Makefile
rm -rf ./src/yapp/worker/Makefile.in
rm -rf ./stamp-h1
rm -rf ./test/yapp/Makefile
rm -rf ./test/yapp/Makefile.in
rm -rf ./test/yapp/admin/Makefile
rm -rf ./test/yapp/admin/Makefile.in
rm -rf ./test/yapp/client/Makefile
rm -rf ./test/yapp/client/Makefile.in
rm -rf ./test/yapp/client/file_input/Makefile
rm -rf ./test/yapp/client/file_input/Makefile.in
rm -rf ./test/yapp/client/id_input/Makefile
rm -rf ./test/yapp/client/id_input/Makefile.in
rm -rf ./test/yapp/conf/Makefile
rm -rf ./test/yapp/conf/Makefile.in
rm -rf ./test/yapp/domain/Makefile
rm -rf ./test/yapp/domain/Makefile.in
rm -rf ./test/yapp/master/Makefile
rm -rf ./test/yapp/master/Makefile.in
rm -rf ./test/yapp/util/Makefile
rm -rf ./test/yapp/util/Makefile.in
rm -rf ./test-driver
